name: lint-and-test

on:
  push:
    branches:
      - "**"
      - "!main"

jobs:
  ci:
    name: lint-and-test

    timeout-minutes: 5
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 7

      - uses: actions/setup-node@v3
        with:
          node-version-file: .tool-versions
          cache: pnpm

      - run: pnpm i --frozen-lockfile

      - run: pnpm run generate

      - run: pnpm run lint-dry

      - run: pnpm run test-ci
